# Generated by Django 2.0.2 on 2018-06-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers_django_models_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttable',
            name='status',
            field=models.IntegerField(choices=[(0, 'Submitted'), (1, 'Inqueue'), (2, 'Complete'), (3, 'Errored')], default=0),
        ),
        migrations.AlterField(
            model_name='uploadedimages',
            name='imageType',
            field=models.CharField(default='jpg', max_length=15),
        ),
    ]
