# Generated by Django 2.0.2 on 2018-06-12 09:05

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resultTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnID_fileHash', models.CharField(max_length=82)),
                ('submitTS', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('completeTS', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Submitted'), (1, 'Received by the model app'), (2, 'In processing queue'), (3, 'Complete')])),
                ('result', jsonfield.fields.JSONField()),
            ],
        ),
    ]
