# Generated by Django 2.0.2 on 2018-06-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooftop_damage_analysis_app', '0002_auto_20180612_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploadedImages',
        ),
    ]
