

#!/bin/sh
export MEDIA_ROOT="/media_root/avengers/media/"
export LOGS_ROOT="/media_root/avengers/logs/"
export DL_MODELS_DIR_ROOT="/media_root/avengers/dl_models/"


export TEST_ENV=true
export PROD_ENV=false


export MONGODB_TEST_HOST="127.0.0.1"
export MONGODB_TEST_PORT=27017
export MONGODB_PROD_HOST="127.0.0.1"
export MONGODB_PROD_PORT=27017

export UPLOAD_SERVICE_TEST_HOST='127.0.0.1'
export UPLOAD_SERVICE_TEST_PORT='8899'

export SHIM_SERVICE_TEST_HOST='127.0.0.1'
export SHIM_SERVICE_TEST_PORT='8900'

export ROOFTOP_DAMAGE_ANALYSIS_TEST_HOST='127.0.0.1'
export ROOFTOP_DAMAGE_ANALYSIS_TEST_PORT='8901'

export CAR_DAMAGE_ANALYSIS_TEST_HOST="127.0.0.1"
export CAR_DAMAGE_ANALYSIS_TEST_PORT='8902'

