# Generated by Django 2.0.2 on 2018-06-13 13:46

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resultTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnID_fileHash', models.CharField(max_length=82)),
                ('submitTS', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('completeTS', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Submitted'), (1, 'Inqueue'), (2, 'Complete'), (3, 'Errored')])),
                ('result', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='uploadedImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageHash', models.CharField(default='default', max_length=32)),
                ('imageType', models.CharField(default='jpg', max_length=15)),
                ('uploadedBy', models.CharField(default='default', max_length=100)),
                ('uploadedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'uploaded_images',
            },
        ),
    ]
