# Generated by Django 2.0.2 on 2018-06-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_upload_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploadedImages',
        ),
    ]
